### ISSUE TITLE
projection stream's antimeridian cutting breaks polygons with holes

### ISSUE THREAD

**Issue by ondras** [d3/d3-geo#102]
Not sure if bug, but it definitely bugs me a lot 😉 

I described the problem I am experiencing in more detail at https://groups.google.com/forum/#!topic/d3-js/1E1_EHPDeKU. It all boils down to the `geoStream -> projectionStream -> [my own consumer]` pipeline, where the "exterior first, interiors second" paradigm for polygons gets broken by antimeridian cutting.

This problem does not manifest when using the default geoPath for svg/canvas.

**Comment by mbostock** [comment]
There is no guarantee that projection streams maintain polygon semantics; see https://github.com/d3/d3/issues/1558#issuecomment-38390031. See also the [d3.geoProject implementation](https://github.com/d3/d3-geo-projection/blob/master/src/project/index.js#L109-L136), which reconstructs polygon semantics.

**Comment by ondras** [comment]
Thanks @mbostock for your prompt and useful response! Re-ordering the rings manually is probably the right way to go.
