### ISSUE TITLE
GeoJSON (RFC 7946) compability

### ISSUE THREAD

**Issue by nunojpg** [d3/d3-geo#104]
I am aware that d3-geo is using a different winding order of legal GeoJSON, but I've come into another problem that I can't explain with this.

To represent the entire north hemisphere in RFC 7946 I use:

```
"geometry": {
    "type": "Polygon",
    "coordinates": [
        [
            [
                -180,
                0
            ],
            [
                180,
                0
            ],
            [
                180,
                90
            ],
            [
                -180,
                90
            ],
            [
                -180,
                0
            ]
        ]
    ]
}
```

To represent it in d3-geo json I use:

```
"geometry": {
    "type": "Polygon",
    "coordinates": [
        [
            [
                0,
                0
            ],
            [
                -90,
                0
            ],
            [
                -180,
                0
            ],
            [
                90,
                0
            ],
            [
                0,
                0
            ]
        ]
    ]
}
```

How is this difference explained, and how can we convert between the two?

Thanks!

**Comment by Fil** [comment]
You can go to http://blockbuilder.org/mbostock/a7bdfeb041e850799a8d3dce4d8c50c8 and paste your d3 (left-handed) polygon in A; then click on the "side by side" button and you'll see both  versions and their consequences.

**Comment by nunojpg** [comment]
@Fil thanks, it is great. I've now got my head around what happens when a small circle grows to become a great circle, and it makes sense. Still don't know how to convert it to legal GeoJSON (RFC7946), as it requires a antimeridian cut.

**Comment by mbostock** [comment]
RFC 7946 uses planar equirectangular coordinates; D3 and TopoJSON use spherical coordinates. 

To convert planar equirectangular coordinates to spherical coordinates, use [d3.geoStitch](https://github.com/d3/d3-geo/blob/master/README.md#geoStitch).

To convert spherical coordinates to planar equirectangular coordinates, use [d3.geoProject](https://github.com/d3/d3-geo-projection/blob/master/README.md#geoProject) from [d3-geo-projection](https://github.com/d3/d3-geo-projection) in conjunction with [d3.geoEquirectangular](https://github.com/d3/d3-geo/blob/master/README.md#geoEquirectangular) with a scale of 1 and a translate of [0, 0].

**Comment by nunojpg** [comment]
@mbostock thanks. It doesn't seem to be that easy, for example with the most basic case:

```
            d3_json = { "type": "Point", "coordinates": [10, 60] }
            proj = d3.geoEquirectangular().translate([0, 0]).scale(1)
            geojson = d3.geoProject(d3_json, proj)
            console.log(geojson)
```
The projected coordinates are [0.17453292519943295, -1.0471975511965976] while they should be the same as in d3_json ([10, 60]).

**Comment by Fil** [comment]
scale = 1 returns gradians; also, pixels are orientated "top to bottom" so you need to inverse the Y axis.

```
var degrees = 180 / Math.PI,
      proj = d3.geoEquirectangular().translate([0,0]).scale(degrees),
      reflect = d3.geoIdentity().reflectY(true),
      antimeridian_cut = function(_) {
	return d3.geoProject(d3.geoProject(_, proj), reflect);
      };

var json = { "type": "LineString", "coordinates": [[170, 60], [-170, 60]] };
console.log(antimeridian_cut(json));
```

**Comment by nunojpg** [comment]
@Fil It seems to work perfectly. Thanks for the code and all the explanations.

**Comment by mbostock** [comment]
Thank you for the correction, @Fil!
