### ISSUE TITLE
geoContains is not working

### ISSUE THREAD

**Issue by psi-gh** [d3/d3-geo#112]
According to `geoContains` method, the center of Moscow is not contained in Moscow Area (it returned `false`), which is a strange fact :) Code snippet to test:
https://runkit.com/embed/cw2rh9zbcbcr
(or in gist https://gist.github.com/psi-gh/6f8e7b356f2bb5086cb98c58fbd0d588)

**Comment by Fil** [comment]
Your polygon appears to be counterclockwise, but d3 expects a clockwise
order (contrary to GeoJSON spec).

http://bl.ocks.org/Fil/263ffe9c05523d2950dac83a44ec1b06

https://github.com/d3/d3-geo/#d3-geo

https://tools.ietf.org/html/rfc7946

**Comment by psi-gh** [comment]
Oh thanks Fil! So i forced to use other library.

**Comment by mbostock** [comment]
You can reverse the coordinates of the polygon rings to flip the winding order.

**Comment by mbostock** [comment]
Standard GeoJSON is planar rather than spherical, so if we implement *path*.contains #109 it would be easy to test for containment using [d3.geoIdentity](https://github.com/d3/d3-geo/blob/master/README.md#geoIdentity) as the projection.

**Comment by iway1** [comment]
probably better off just using this: `https://stackoverflow.com/questions/22521982/check-if-point-is-inside-a-polygon`

geoContains some times does not even work when the coords are counter clockwise. =/
