### ISSUE TITLE
d3.geoBounds() failes to obtain correct latitude/longitude values

### ISSUE THREAD

**Issue by BastiTee** [d3/d3-geo#118]
Hi there,
I am working with d3-geo trying to draw a map of Bonn/Germany. After I failed to correctly scale the map I found that either my data is somehow malformed, a necessary data-sanitization step is not available or d3-geo maybe has a bug. 

The minimal example can be found here: https://bl.ocks.org/BastiTee/23e05990a761b4d616ae42d0ed036307 

As you can see, I only load the data from `bonn.json` and print the result of d3.geoBounds. The values (-180,-90 | 180,90) are incorrect. 

Using both http://mapshaper.org/ and http://geojsonlint.com/ I am able to load the data without any error, displaying the map correctly. If I put in other map data into my code I see realistic lat/long values. I manually checked and there is nothing outside the 50.* or 7.* range.
Even in the [gist itself](https://gist.github.com/BastiTee/23e05990a761b4d616ae42d0ed036307#file-bonn-json), the data is mapped correctly. 

I crossposted this to [stackoverflow](https://stackoverflow.com/questions/46420662/d3-geobounds-failes-to-obtain-correct-latitude-longitude-values-wrong-usage-o). 

Thanks in advance.

**Comment by BastiTee** [comment]
If I hardcode the expected value `var bounds = [[7.0226282622, 50.6327277725], [7.2106608053, 50.7743702078]]` the remaining code works like expected. It boils down to this particular call.

**Comment by mbostock** [comment]
Did you check the [winding order](https://bl.ocks.org/mbostock/a7bdfeb041e850799a8d3dce4d8c50c8) of your polygons? Per the README, D3 and standard GeoJSON have different winding order conventions (because D3 uses spherical coordinates and most other GeoJSON tools assume planar equirectangular coordinates).

**Comment by BastiTee** [comment]
I just reversed the coordinates and – that did the trick. 
Thank you very much for your quick response and all the best!
