### ISSUE TITLE
[Doc] Clarifying wording for Clipping Functions

### ISSUE THREAD

**Issue by tomwanzek** [d3/d3-geo#119]
The documentation for the newly added clipping functions (`geoClipAntimeridian`, `geoClipCircle`, `geoClipRectangle`) in the `README` starts with:

> Returns a stream where geometries...

Should the wording be changed to:

> Returns a clipping function which accepts a stream as input and transforms it to a stream where geometries...

or even shorter

> Returns a clipping function transforming a stream such that geometries...

?

**Comment by Fil** [comment]
Those symbols are a bit different:

— `geoClipAntimeridian` _is_ a clipping function, it does not return one. It reads a stream as input and returns a transformed stream. 
Your remark would not apply to this symbol. 

— `geoClipCircle` is a function that reads an `angle` and _returns_ a clipping function. (Same for `geoClipRectangle` and `geoClipPolygon`).
In this case, I agree that the sentence's subject is unclear. I like your second wording. It could also be "Generates a clipping function that transforms…".

**Comment by tomwanzek** [comment]
Agreed. They are slightly different (tried to be shorter in my issue filing than I should have).

`geoClipAntimeridian` could simply be:

> A clipping function transforming a stream such that geometries...
