### ISSUE TITLE
Inconsistent rendering between standalone version of d3-geo and main d3 bundle

### ISSUE THREAD

**Issue by afdta** [d3/d3-geo#133]
I created a simple world country map and initially had problems with some paths not closing properly. I used the d3.geoEquirectangular() projection in the main D3 bundle (version 4.13.0). I subsequently tried adding the d3-geo module to the page, which appeared to fix the issue. I assume the standalone module is a newer version? 

Post on Stackoverflow: [https://stackoverflow.com/questions/49312172/inconsistent-rendering-of-map-by-d3-geoequirectangular](https://stackoverflow.com/questions/49312172/inconsistent-rendering-of-map-by-d3-geoequirectangular)

**Comment by afdta** [comment]
I believe this duplicates https://github.com/d3/d3-geo/issues/105

**Comment by Fil** [comment]
Wow — thank you for this confirmation with a very straightforward example.
