### ISSUE TITLE
Weird canvas render after setting projection's center

### ISSUE THREAD

**Issue by gaohailang** [d3/d3-geo#136]
If i set projection's center diff from [0,0], the canvas is not rendered completed.
how can i handle this problem, thanks for help!

```
projection2 = d3.geoMercator().translate([width / 2, height / 2]).scale((1 << 8 + 3) / 2 / Math.PI).center([80, 0])
```
![image](https://user-images.githubusercontent.com/697853/40581854-687a09b0-6195-11e8-8609-c058b2607b94.png)

```
projection2 = d3.geoMercator().translate([width / 2, height / 2]).scale((1 << 8 + 3) / 2 / Math.PI).center([0, 0])
```

![image](https://user-images.githubusercontent.com/697853/40581853-63ca5a96-6195-11e8-93de-94e5e2f48ad9.png)

**Comment by hudsonb** [comment]
That's working as I'd expect. Maybe you mean to rotate by λ instead? 

This block is great for exploring projections and seeing how the various parameters effect the output: https://bl.ocks.org/d3indepth/f7ece0ab9a3df06a8cecd2c0e33e54ef

**Comment by gaohailang** [comment]
@hudsonb yeah. rotate λ is exactly what i needed. and the visualization block tool helps me a lot for understanding the projection transform. thanks a lot!
