### ISSUE TITLE
path is not generated correctly

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [d3/d3-geo#142]
here is an example of what is happening:
https://codesandbox.io/s/k0r37p4455

**Comment by egor-a-trubnikov-panov** [comment]
must be.:https://codesandbox.io/s/n36pkjnjnj

**Comment by Fil** [comment]
The polygon in the first example appears to be defined counter-clockwise, while d3 expects it to be clockwise (see " winding order convention" in https://github.com/d3/d3-geo/ ). A counter-clockwise polygon will draw a map covering the whole sphere, with a hole corresponding to the polygon's edges.
