### ISSUE TITLE
Clipping + thicker SVG strokes + Chrome HW acceleration = geometry leaking bug

### ISSUE THREAD

**Issue by iafan** [d3/d3-geo#143]
I think I found what constitutes a Chrome bug, but since it affects and was discovered by using d3-geo, I think it makes sense to report it here for better visibility and in case you can find a workaround for it in the clipping code.

Here's the Chromium issue I filed: https://bugs.chromium.org/p/chromium/issues/detail?id=851637 (it contains a zip file with the sample project).

Here's the video that shows how the bug manifests itself: https://youtu.be/ee_LeTAH1qo

What I'm doing in the example code is I'm setting up a scene where I calculate a geodesic mesh and then put a geoCircle at each vertex. The projection I use is geoAzimuthalEqualArea, with clipping. Circles are  added as SVG paths (I use SVG instead of canvas because in the larger project I want some interaction and transitions). These SVG paths have CSS styles applied (fill + 2px stroke). Then I start rotating the sphere, which causes paths to go beyond and reappear from behind of a 'horizon'. So I believe is that the combination of very small path geometry combined with thicker strokes is what causes issues in Chrome.

If I remove the 2px stroke (leave the default outline one), the problem is gone. If I remove projection clipping, the problem is also gone.

Note that this only happens in Chrome (tested on latest 67/Mac/stable and 68/Mac/beta builds) and latest stable Electron, when hardware acceleration is enabled (which is by default). The issue doesn't happen in Safari or Firefox. So while the issue is browser-specific, the affected combination represents the majority of browser users.

I wonder if d3-geo can do something to work around this problem, like adjusting the clipping code to filter out paths less than a certain threshold in side (since they will not likely be visible, anyway).

The only slightly related issue I've found is https://github.com/d3/d3-geo/issues/54 where another edge case check is made.

**Comment by Fil** [comment]
Here's a minimalist demo for the bug

```
<style>
svg {
  width: 1500px;
}
path {
  stroke-width: 2px;
  stroke: #345;
}
</style>

<svg>
<path
d="M509.3,105.2L509.1,105.0L507.5,103.4L504.4,99.8L503.0,97.8L501.6,95.6L497.9,88.7L496.9,86.3L496.0,83.9L495.2,81.5L494.5,79.2L494.1,76.9L493.7,74.6L493.6,73.8L493.6,73.8L499.9,85.0L505.5,96.4Z"
></path>
</svg>
```

It looks like switching 499.9 to 499.5 or 500 makes the bug disappear, which lead me to this solution:
```
var path0 = d3.geoPath().projection(projection);

var path = d => {
	var p = path0(d);
	if (p) return p.replace(/\.[5-9]\d+/g, '.5').replace(/\.[0-4]\d+/g, '')
}
```

(It could be wrapped more neatly.)

As it's a generic problem with SVG in those versions of Chrome, I don't believe this is something that `d3-geo` should take into account.
