### ISSUE TITLE
pseudo cylindrical projection ([100000, 0]) explodes

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo#147]
You can see this by changing https://beta.observablehq.com/@mbostock/spherical-fibonacci-lattice to `projection = d3.geoEqualEarth()` 
=> https://beta.observablehq.com/d/cb1e36fa5526761c

this is due to rotation.js not taking care of the case `abs(lambda) > 3 pi`

A fix could be
```
function rotationIdentity(lambda, phi) {
-  return [lambda > pi ? lambda - tau : lambda < -pi ? lambda + tau : lambda, phi];
+  [lambda > pi ? (lambda + pi) % tau - pi : lambda < -pi ? (lambda - pi) % tau + pi : lambda, phi];
}
```

<del>(not tested).</del>
EDIT: tested

Or, to fix only the notebook, replace `x * 360` : `(x * 360) % 360`.

**Comment by mbostock** [comment]
I fixed my notebook…

**Comment by Fil** [comment]
Should we fix d3-geo too? It doesn't seem costly.

**Comment by Fil** [comment]
Note: as all (pseudo) cylindrical projections (where `x = f(phi) * lambda`) are concerned with this issue, the release comment could be 
> More robust pseudo-cylindrical projections.
