### ISSUE TITLE
weird preclip behavior

### ISSUE THREAD

**Issue by esperanc** [d3/d3-geo#149]
I was adapting this [Observable notebook by F. Lederman](https://beta.observablehq.com/@floledermann/drawing-maps-from-geodata-in-d3) to handle a geojson dataset containing neighborhoods from the city of Rio de janeiro and noticed that `.preclip()`exhibited a weird behavior. Namely, it seems to think that some small regions are bigger than the whole globe. To fix it, I had to add a `.preclip (x => x)` to the definition of the projection function (see the `projection` cell in the [adapted notebook](https://beta.observablehq.com/@esperanc/limites-de-bairros-do-rio-de-janeiro)) so that the projection would work correctly. Removing the preclip from the projection definition is enough to reproduce the problem. I may be missing something, but it looks like a bug...

**Comment by Fil** [comment]
Hello Claudio,

it seems that your original file has the wrong winding order (see https://github.com/d3/d3-geo). 

Here's a way to fix it: https://beta.observablehq.com/d/d8f95742d2ab7d99#data ; it's a common pain point with GeoJSON, unfortunately.

**Comment by esperanc** [comment]
Hmm. I get it. However, according to the [Geojson specification](https://tools.ietf.org/html/rfc7946#section-3.1.6), the winding order for the external rings should be right-hand oriented, which I assumed would mean counterclockwise. My own tests indicate that my data would then conform to this. Perhaps I'm missing something. I also note that the specification says that for compatibility the parser should not be picky about winding orders. 

I tried to investigate the issue further by repeating the test with the `ny.json` file in this project. It uses clockwise external rings, which seems to be the case d3-geo assumes correct. I've included this test in the [my notebook](https://beta.observablehq.com/@esperanc/limites-de-bairros-do-rio-de-janeiro) in case anyone is interested.

**Comment by Fil** [comment]
Yes, it's a mess. For d3-geo's homepage:

> Spherical polygons also require a winding order convention to determine which side of the polygon is the inside: the exterior ring for polygons smaller than a hemisphere must be clockwise, while the exterior ring for polygons larger than a hemisphere must be anticlockwise. Interior rings representing holes must use the opposite winding order of their exterior ring. This winding order convention is also used by TopoJSON and ESRI shapefiles; however, *it is the opposite convention of GeoJSON’s RFC 7946. *
