### ISSUE TITLE
geoContains for LineStrings incorrect?

### ISSUE THREAD

**Issue by ondras** [d3/d3-geo#154]
Somewhat related to #153 -- the [implementation of `containsLine`](https://github.com/d3/d3-geo/blob/master/src/contains.js#L61) seems to only check the first two pairs of coordinates in a LineString. A LineString can be much longer, so probably all line segments shall be checked (for the first proximity match).

**Comment by mbostock** [comment]
Yeah, that looks like a bug.

**Comment by Fil** [comment]
Merged, thank you @ondras!
