### ISSUE TITLE
geoInterpolateRotation?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo#158]
It would be great to have a spherical linear interpolation implementation, as shown here:

https://observablehq.com/@d3/world-tour

**Comment by Fil** [comment]
I've tried to upgrade [versor](https://github.com/Fil/versor) to your new code, but it escapes me how we can compute `versor.delta()` — which is very much needed for the "inertia" thing.
https://github.com/Fil/versor/commit/93847b63f56d4eb7c6b3b0706170ece186d40b04

**Comment by Fil** [comment]
versor@0.1 now includes the code from @d3/world-tour and can be used to do SLERP.

**Comment by Fil** [comment]
This is also covered by attitude https://github.com/fil/attitude
