### ISSUE TITLE
d3.geoBounds fails on Sphere type?

### ISSUE THREAD

**Issue by jheer** [d3/d3-geo#163]
If I try this: `d3.geoBounds({type: "Sphere"})`

I get this: `Uncaught TypeError: n.sphere is not a function`

... and similarly for `d3.geoBounds({type: "Feature", geometry: {type: "Sphere"}})`

Is this perhaps due to a missing implementation of a `sphere` function on a stream interface?

**Comment by Fil** [comment]
Will be fixed in the next release. Thank you!
