### ISSUE TITLE
Bug / limitation? d3.geoContains returns false for point in big rechtangle

### ISSUE THREAD

**Issue by baslr** [d3/d3-geo#169]
```js
const a = {   "type": "Feature",
    "properties": {},
    "geometry": {
      "type": "Polygon",
      "coordinates": [[[-100, 60],
          [-100,0],
          [90,0],
          [90,60],
          [-100,60]]]}}

d3.geoContains(a, [6.939945, 50.932222]) // point in cologne, germany
// false
```
Polygon, germany is inside
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/1494154/60395359-5fd55f80-9b32-11e9-94fa-8b995b5dc606.png">

Maybe someone has a hint?

xref: arangodb/arangodb/issues/9352

**Comment by baslr** [comment]
```
const turf = require('@turf/turf');

const a = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Polygon",
    "coordinates": [[[-100, 60],
    [-100, 0],
    [90, 0],
    [90, 60],
    [-100, 60]]]
  }
}

const pt = turf.point([6.939945, 50.932222]);
const res = turf.booleanPointInPolygon(pt, a);
console.log(res); // true
```

**Comment by Fil** [comment]
d3-geo uses spherical WSG84 coordinates and edges of a polygon are computed as great-circle shortest paths between successive vertices. It also uses a certain winding convention (see the introduction of https://github.com/d3/d3-geo).

Which means that this polygon defines the blue region on the following map. 

![untitled (17)](https://user-images.githubusercontent.com/7001/60399340-63cda580-9b63-11e9-8dfa-3c23660471c6.png)
