### ISSUE TITLE
albersUsa 

### ISSUE THREAD

**Issue by mojobnichols** [d3/d3-geo#171]
I got a request to make Alaska a little larger.   I see that I can change the code but I'd like something a bit more permanent so it's default would be 0.35, but it could be set to something else if desired.    I saw one other person on the internet solved it by simply changing the source, so I'm not the only one.   I'd be happy to make the contribution.

Thanks

**Comment by mbostock** [comment]
You are welcome to copy the source of geoAlbersUsa and change the layout. However, I don’t think we can easily support configuring the size of Alaska in the general case because it would complicate how we implement invert and make it easy for Alaska to overlap with other features.

**Comment by mojobnichols** [comment]
Point taken, I will make a copy add the feature and see if it's simple enough to override in the case of invert.  As for overlapping features, I think some Alaskans would be fine with that;-).   But really if you use the feature and you create a situation of Alaska overlapping some other feature that's on the user.  I'll share my thoughts after implementing maybe you'll want to incorporate.  

On making a copy, do you know how I would make a copy store in my source and force d3-geo to pickup my copy?  Obviously just changing the source in my installed node modules doesn't work as the next update will override it. Answer if you have time, I can dig into it.  I appreciate your help and expertise.

**Comment by mbostock** [comment]
You can see an example here:

https://bl.ocks.org/HarryStevens/0e440b73fbd88df7c6538417481c9065

And the source:

https://gist.githubusercontent.com/HarryStevens/0e440b73fbd88df7c6538417481c9065/raw/0e30c94bd5cdecf3bbf56e3c2ddeb0bc9dc0164f/albers-usa-pr.js

Basically, you define a new projection, and you reference that projection rather than trying to redefine d3.geoAlbersUsa.

**Comment by mbostock** [comment]
Also, I’d consider a PR to increase the size of Alaska in a *non-configurable* way, if there’s an argument that the current design of geoAlbersUsa is committing cartographic sin or slighting Alaskas by representing it in an excessively diminutive way. I believe that the current implementation is comparable with The New York Times current practice, *e.g.*

![image](https://user-images.githubusercontent.com/230541/63178298-9f7eda80-bffe-11e9-8d67-ad84808553a6.png)

But I believe they use a cylindrical projection for Alaska (possibly even Mercator?), hence the straight right edge, and I always thought that was a weird choice, so D3 uses [Alaska Albers](http://epsg.io/3338).

**Comment by mbloch** [comment]
Hi Mike,

The NYT uses a conic projection for Alaska (usually Lambert CC). We're not very consistent about rotation (i.e. the central meridian). Some of our maps use 141°W, which gives a vertical line along the long straight eastern boundary, like in the map that you pasted above. I usually use 152°W, which puts the central meridian about in the middle of the AK inset.

I've noticed that other cartographers use different values for the central meridian when insetting Alaska. There doesn't seem to be a consensus value.

**Comment by mbostock** [comment]
Hi @mbloch! Thanks for the clarification! ❤️

**Comment by jrus** [comment]
> The NYT uses a conic projection for Alaska (usually Lambert CC). 

You mix an equal-area projection for the states with a conformal projection for Alaska?

Why not pick some equal-area projection for Alaska as well? (Even if the scale is going to be a bit different.)

**Comment by mbloch** [comment]
Hi @jrus ,

I don't think it matters much if the NYT uses Lambert CC (lcc) or Albers (aea) for Alaska insets.

For one thing, we're already violating the equal area principle by rescaling Alaska.

It's true that using lcc does affect the relative size of Alaska subdivisions, but the difference is very small, provided you use reasonable values for the standard parallels. I just checked using a Census tracts layer. Lambert has less than 1% areal distortion for almost all parts of the state -- almost equal area, and not a noticeable difference.

To be clear, I think that d3 should continue to use Albers for the Alaska inset in the "AlbersUSA" projection.
