### ISSUE TITLE
Release d3-array v2 compatible version?

### ISSUE THREAD

**Issue by jheer** [d3/d3-geo#176]
It would be wonderful to have a version of d3-geo that works with d3-array v2 to avoid multiple version issues in downstream projects. I see that the dependency in package.json has already been updated along these lines, so I was hoping a corresponding release might be forthcoming? Thanks!

**Comment by Fil** [comment]
I have released it on npm and drafted a release in https://github.com/d3/d3-geo/releases/tag/untagged-43dcdda18e7b2a650d96; however d3-geo v1 must also be copied to the d3js.org website, so I'll need help from @mbostock to finish this task .

**Comment by Leannechn** [comment]
d3-array v2  dist/* not es5.
When use webpack uglify，export error：unexpexted name count

**Comment by Fil** [comment]
@Leannechn if you need ES5 you should stick with d3-array 1.x or use a transpiler, as noted in https://github.com/d3/d3-array/releases/tag/v2.0.0

**Comment by Leannechn** [comment]
The x-bit upgrade will be upgraded automatically. Causes many projects to need to supplement the locked version

> @Leannechn if you need ES5 you should stick with d3-array 1.x or use a transpiler, as noted in https://github.com/d3/d3-array/releases/tag/v2.0.0

**Comment by Leannechn** [comment]
云构建项目都自动升级x位版本号，并报错。这种做法不安全。
The cloud build project automatically upgrades the x-bit version number and reports an error. This is unsafe

**Comment by Fil** [comment]
As evidenced by @Leannechn 's messages, this might need to be reverted and postponed for a d3-geo@2 version (which would embrace ES6). I'm not sure what to do.

**Comment by Leannechn** [comment]
I hope that the automatic upgrade version will be stable.

**Comment by Leannechn** [comment]
Sorry, I am more anxious to fix.

**Comment by Leannechn** [comment]
Maybe can change npm latest version to 1.11.6 。And keep  1.11.7。I need to deal with the impact quickly

**Comment by Leannechn** [comment]
@mbostock Really anxious, it’s hard to lock the version for deep-dependent projects。
Can you give priority to discuss it?

**Comment by mbostock** [comment]
Yeah, I think it makes sense to do a major version bump.

**Comment by Leannechn** [comment]
So what is the solution?

**Comment by ZhangJinH** [comment]
I have the same problem When Webpack compiling my project,..waiting for the solution, :)

**Comment by Fil** [comment]
I have released [v1.11.8](https://github.com/d3/d3-geo/releases/tag/v1.11.8) which should fix this webpack panic. Closing this issue now—in favor of https://github.com/d3/d3-geo/issues/179
