### ISSUE TITLE
Dependencies d3-array export error：unexpexted name count. Lock the version to v1 until it is fixed

### ISSUE THREAD

**Issue by Leannechn** [d3/d3-geo#177]
when use webpack and uglify

**Comment by Fil** [comment]
See https://github.com/d3/d3-array/releases/tag/v2.0.0

**Comment by Leannechn** [comment]
> See https://github.com/d3/d3-array/releases/tag/v2.0.0

So，the version number will take some project auto upgrade 。
to be 1.12.x will be better

**Comment by Leannechn** [comment]
Maby 2.x  version number  will be better

**Comment by Leannechn** [comment]
1.11.6 VS 1.11.7  unsupport pre-ES2015 environments, so much change~ version number is ok

**Comment by Fil** [comment]
Discussed in #176
