### ISSUE TITLE
Help:  1.11.6 to 1.11.7 the dependencies change UNSAFE ! Hope change back to d3-array v1. And publish d3-geo@2.x with d3-array v2 

### ISSUE THREAD

**Issue by Leannechn** [d3/d3-geo#178]
云构建项目都自动升级z位版本号，并报错。这种做法不安全。
The cloud build project automatically upgrades the z-bit version number and reports an error. This is unsafe.
我们依赖了d3-geo. 有很多项目依赖了我们的包。这样不安全的升级 导致一些不可控的问题。
We release on d3-geo. There are many projects that depend on our package. This unsafe upgrade leads to some uncontrollable problems.

**Comment by Fil** [comment]
This is a linked to #176 and is discussed there ; please refrain from posting more issues on the same topic.
