### ISSUE TITLE
Release d3-array v2 compatible version

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo#179]
@jheer suggested in #176:
> It would be wonderful to have a version of d3-geo that works with d3-array v2 to avoid multiple version issues in downstream projects. I see that the dependency in package.json has already been updated along these lines, so I was hoping a corresponding release might be forthcoming? Thanks!

However as we saw, this creates errors in webpack projects: automatic updates then use d3-array@2 which has switched to ES6.

As a consequence, this change will need to wait for a major version bump (to d3-geo@2).

**Comment by jheer** [comment]
Makes sense, thanks. Any ETA on when the major version bump might be released? I agree that preventing breakage takes priority, but the current inconsistencies across D3 modules results in bundles that include multiple versions of the d3-array library.

**Comment by Fil** [comment]
We could do d3-geo@2.0.0 now, proclaiming it ES6 (and probably adding at least one line of ES6 to it so that it breaks webpack immediately :)) — but I believe the correct answer is linked to progress on d3v6, so not really for me to say.

**Comment by Leannechn** [comment]
Why not keep es5 & es6 both.  d3-array too.
config as that
![image](https://user-images.githubusercontent.com/6812138/68750975-bc499f00-063b-11ea-86fc-8f2e5fdd2970.png)

**Comment by Fil** [comment]
Branch *two* (https://github.com/d3/d3-geo/pull/202) now addresses this. ETA at the end of the June.

@Leannechn the adoption of ES6 will be marked by a major version change (v2). We have no plans to ship transpiled ES5 code; users needing ES5 would either have to stay with v1 or transpile v2 at build.
