### ISSUE TITLE
Experiment with lebab (transpiling *to* ES6)

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo#180]
As an experiment (prompted by https://github.com/d3/d3-geo/issues/179), I applied [lebab](https://github.com/lebab/lebab) to d3-geo, which resulted in the branch `es6` in https://github.com/Fil/d3-geo/commits/es6

I've used a private fork because I don't think we want this for d3-geo.

Fun results though: the build loses 2.1% & minified build loses 2.9%.

ES5:
- 88441 d3-geo.js
- 35626 d3-geo.min.js

ES6:
- 86528 d3-geo.js
- 34590 d3-geo.min.js

### log

~~~
for rule in arrow arrow-return for-of for-each arg-rest arg-spread obj-method obj-shorthand no-strict let; do
  lebab --replace 'src/**/*.js' --transform $rule
  yarn test && git commit -a -m"lebab --replace 'src/**/*.js' --transform $rule"
done
~~~

patch for the rule `let`
ignore the rule `class`

~~~
for rule in commonjs template ; do
  lebab --replace 'src/**/*.js' --transform $rule
  yarn test && git commit -a -m"lebab --replace 'src/**/*.js' --transform $rule"
done
~~~

rule `default-param` needs a fix for src/clip/rectangle.js
ignore rule `destruct-param` (same issue as rule `default-param`)

~~~
for rule in  includes ; do
  lebab --replace 'src/**/*.js' --transform $rule
  yarn test && git commit -a -m"lebab --replace 'src/**/*.js' --transform $rule"
done
~~~

**Comment by mbostock** [comment]
I am strongly opposed to shipping transpiled-to-ES5 code. This will not be reliable, and not something that I want to spend effort supporting.

**Comment by gordonwoodhull** [comment]
@Fil transpiled it to ES6!

**Comment by mbostock** [comment]
Oh, I totally misread, sorry!

**Comment by Fil** [comment]
(no need to keep this open)
