### ISSUE TITLE
Expose a function for geoIdentity

### ISSUE THREAD

**Issue by martgnz** [d3/d3-geo#182]
With a normal projection you can pass a set of coordinates so, `projection([coords.long, coords.lat])` returns _x_ and _y_ screen coordinates.

geoIdentity, on the other hand, doesn't expose that function. This would be useful for translating preprojected geometry that has been fitted to a certain screen size with fitSize (for example https://observablehq.com/@clhenrick/d3-geoidentity).

With this it would be easier to, for example, find out the _x_ and _y_ coordinates of a set of preprojected points for passing them to d3-delaunay.

I guess this would be more consistent with the other projections, too.

**Comment by Fil** [comment]
maybe instead of https://github.com/d3/d3-geo/blob/master/src/projection/identity.js#L27 we should add all these properties to a function that does https://github.com/d3/d3-geo/blob/master/src/projection/identity.js#L9 ? 🤔

**Comment by Fil** [comment]
fixed in https://github.com/d3/d3-geo/commit/cfa90693d7f9744ff1100592badc1cdbaef7f36e ; thanks!
