### ISSUE TITLE
Support to get bounding lat/lng after zoom and scale for visible area in screen

### ISSUE THREAD

**Issue by stripathix** [d3/d3-geo#188]
Using observable by @Fil  as a reference to create a globe on canvas.

https://observablehq.com/d/7a912fba32fbe641

Screen looks like:
<img width="689" alt="Screenshot 2020-03-07 at 11 15 43 AM" src="https://user-images.githubusercontent.com/8480351/76156115-8d3fc780-611b-11ea-919d-19f4cb391e03.png">

Facing issues here:

- How to get bounding box lat/long for the globe. I mean when we zoom in than how to know what is the lat/lng bounding box coordinates.

While using leaflet there were API functions exposed that can be easily called to get bounding box.

Use case: On zoom-in I want to call an API that returns airports in a given visible area. To do that I want to get a lat/lng bounding box on the screen.

The bound function that is already available expects GeoJSON object but here to get the bounding box for the given visible region on the screen I don't have any GeoJSON object.

**Comment by mbostock** [comment]
Depending on the projection, it’s not going to be a bounding box. That would only be the case for a cylindrical projection.

If you want a general method that will work with any projection, you can use a custom projection stream that tests whether a particular point would be displayed (or clipped). Here’s an example:

https://observablehq.com/@d3/testing-projection-visibility

**Comment by stripathix** [comment]
This does work with a list of points but the problem comes when the globe is being zoomed. 

Using stream filter it does filter out points that are not visible when I rotate the globe but a point can also go out of the visible region if zoom is been done on the globe.

For example, there is a POINT in New York but and as per rotation angle whole USA is visible in this case it filters right if I rotate the globe to Australia. But it should also filter New York point, if I don't rotate globe but zoom-in to Las Vegas. In this case, also New-York's point is not visible on the screen. Can that be done?

**Comment by Fil** [comment]
> zoom-in to Las Vegas. In this case, also New-York's point is not visible on the screen 

Probably add `projection.clipExtent([[0, 0], [width, height]]);` before you call the tester function.

To compute the geo bounding box you need to call the API is quite a bit trickier: in https://observablehq.com/d/1ce15aca13608a14 I do an inverse projection of all the points of the projected {type: "Sphere"} (with a clipExtent), and return the geoBounds of those spherical coords.

**Comment by Fil** [comment]
<img width="700" alt="Capture d’écran 2020-03-08 à 11 58 08" src="https://user-images.githubusercontent.com/7001/76161484-1c58d980-6134-11ea-9b33-2e36692ca6f9.png">

**Comment by Fil** [comment]
I've updated the notebook with a better strategy, now it seems to work in all cases. It just needs a better title & could be published.
