### ISSUE TITLE
Performance issue with a shape file (.shp)

### ISSUE THREAD

**Issue by stripathix** [d3/d3-geo#192]
I a trying to render shapefile (.shp) on my globe :) but it takes too long to render and once rendered it kills the performance of globe rotation and zooming.

Here is how it looks after rendered.
<img width="682" alt="Screenshot 2020-04-04 at 3 08 15 PM" src="https://user-images.githubusercontent.com/8480351/78423713-e1d85300-7685-11ea-95c2-9f8f8cf0e342.png">
<img width="488" alt="Screenshot 2020-04-04 at 3 08 57 PM" src="https://user-images.githubusercontent.com/8480351/78423717-f3215f80-7685-11ea-902a-816538acd914.png">

Shapefile I am using is:
[Sample 1.zip](https://github.com/d3/d3-geo/files/4431090/Sample.1.zip)

Steps I do for testing is 
1) Upload my shapefile to online to [mapshaper](https://mapshaper.org/) that converts it to topojson
2) Then render that topojson as below code. 
Here is topojson file exported.
[shpjson.json.zip](https://github.com/d3/d3-geo/files/4431097/shpjson.json.zip)

```
// shpTopoJsonData is data I get from mapshaper which is topojson data converted from .shp file
var shpJson = window.topojson.mesh(shpTopoJsonData);

   /// Function to draw topojson
    content.drawShapeFile = function (ctx, path, shpJson) {
        ctx.beginPath();
        path(shpJson);
        ctx.lineWidth = 1;
        ctx.strokeStyle = "red";
        ctx.stroke();
    };
```

**Comment by curran** [comment]
Have you tried the simplify option of Mapshaper?

Likely there are just too many points - for any software - for it to be performant.

The simplify option in Mapshaper reduces the number of points, but preserves larger shapes.

**Comment by Fil** [comment]
https://observablehq.com/@d3/versor-zooming shows how you can use a simplified version for a faster rendering during the rotation gesture.

**Comment by stripathix** [comment]
@curran yeah that's true its too large data. I tried a simplify option too which reduced the file size to 1.5mb but still it has too much of points :-(
As @Fil  pointed out that in versor-zooming different data is used while zooming and zoom-end. But even 0% simplified data is slow maybe I need to do something that actually mapshaper.org is doing while rendering output. because their zooming is pretty smooth.
