### ISSUE TITLE
Support to draw a PNG over Canvas projection of globe 

### ISSUE THREAD

**Issue by stripathix** [d3/d3-geo#195]
I am Using observable by @Fil  as a reference to create a globe on canvas.

https://observablehq.com/d/7a912fba32fbe641

The screen looks like:
![image](https://user-images.githubusercontent.com/8480351/80520613-51044700-89a7-11ea-9a98-a66ae4e62ba5.png)

Using a library https://gdal.org/index.html to convert grib2 file to PNG
![test](https://user-images.githubusercontent.com/8480351/80520773-8a3cb700-89a7-11ea-8afe-5c96e2a060f3.png)

It does provide information that what are the coordinates across which this PNG should be drawn.
**Its Corner Coordinates:**
**Upper Left  (-130.0000000,  55.0000000) (130d 0' 0.00"W, 55d 0' 0.00"N)
Lower Left  (-130.0000000,  20.0000010) (130d 0' 0.00"W, 20d 0' 0.00"N)
Upper Right ( -60.0000020,  55.0000000) ( 60d 0' 0.01"W, 55d 0' 0.00"N)
Lower Right ( -60.0000020,  20.0000010) ( 60d 0' 0.01"W, 20d 0' 0.00"N)
Center      ( -95.0000010,  37.5000005) ( 95d 0' 0.00"W, 37d30' 0.00"N)**
Band 1 Block=7000x1 Type=Float64

All information
```
gdalinfo MRMS_ReflectivityAtLowestAltitude.latest.grib2
Driver: GRIB/GRIdded Binary (.grb, .grb2)
Files: MRMS_ReflectivityAtLowestAltitude.latest.grib2
Size is 7000, 3500
Coordinate System is:
GEOGCS["Coordinate System imported from GRIB file",
    DATUM["unknown",
        SPHEROID["Spheroid imported from GRIB file",6378160,298.2539162964695]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]]
Origin = (-129.999999999857124,54.999999999857103)
Pixel Size = (0.009999999714245,-0.009999999714204)
Corner Coordinates:
Upper Left  (-130.0000000,  55.0000000) (130d 0' 0.00"W, 55d 0' 0.00"N)
Lower Left  (-130.0000000,  20.0000010) (130d 0' 0.00"W, 20d 0' 0.00"N)
Upper Right ( -60.0000020,  55.0000000) ( 60d 0' 0.01"W, 55d 0' 0.00"N)
Lower Right ( -60.0000020,  20.0000010) ( 60d 0' 0.01"W, 20d 0' 0.00"N)
Center      ( -95.0000010,  37.5000005) ( 95d 0' 0.00"W, 37d30' 0.00"N)
Band 1 Block=7000x1 Type=Float64, ColorInterp=Undefined
  Description = 500[m] GPML="Specific altitude above mean sea level"
  Metadata:
    GRIB_COMMENT=ReflectivityAtLowestAltitude [dBZ]
    GRIB_DISCIPLINE=209
    GRIB_ELEMENT=ReflectivityAtLowestAltitude
    GRIB_FORECAST_SECONDS=0 sec
    GRIB_IDS=CENTER=161(US-OAR) SUBCENTER=0 MASTER_TABLE=255 LOCAL_TABLE=1 SIGNF_REF_TIME=3(Observation_time) REF_TIME=2020-04-28T17:34:36Z PROD_STATUS=2(Research) TYPE=7(Processed_radar_observations)
    GRIB_PDS_PDTN=0
    GRIB_PDS_TEMPLATE_ASSEMBLED_VALUES=3 57 8 0 97 0 0 0 0 102 0 500 255 1 0
    GRIB_PDS_TEMPLATE_NUMBERS=3 57 8 0 97 0 0 0 0 0 0 0 0 102 0 0 0 1 244 255 1 0 0 0 0
    GRIB_REF_TIME=  1588095276 sec UTC
    GRIB_SHORT_NAME=500-GPML
    GRIB_UNIT=[dBZ]
    GRIB_VALID_TIME=  1588095276 sec UTC
```

How can I draw this PNG to 3d globe? I am not able to figure it out. Is it something that can be done through d3.geo?  Maybe it will be raster pixel mapping with lat/lng.

Like positioning PNG over the globe across given coordinates. Couldn't find helpful information in docs.

**Comment by Fil** [comment]
raster projection is (for the time being) outside the scope of d3-geo; however you might have luck with one of 
- https://observablehq.com/@harrystevens/raster-reprojection
- https://observablehq.com/@fil/cordiform-glsl
- https://observablehq.com/@mbostock/raster-reprojection-ii

**Comment by stripathix** [comment]
Thanks, @Fil for the suggestion
