### ISSUE TITLE
Failure to plot / Complex geometries issue?

### ISSUE THREAD

**Issue by mshodge** [d3/d3-geo#204]
Hi there,

I'm using D3-geo to create choropleth maps in Google Data Studio. For UK boundaries it seemed to work fine, but someone else tried to use it on Google's US Counties data set and Australia's Suburb data set and both did not plot the data properly.

[See this as an example.](https://datastudio.google.com/reporting/d991445c-a6ab-4bec-9376-8d6f93467b10)

<img width="602" alt="Screenshot 2020-06-14 at 20 31 00" src="https://user-images.githubusercontent.com/15108577/84602256-f737dd80-ae7d-11ea-8517-60e31012b3f0.png">

The plots created show a single boxed polygon. If you change the slider to be 690 <-> 3,743 the polygons that fit this filter work fine (the filter is the length of the geometry string that is used to create the plot).

<img width="623" alt="Screenshot 2020-06-14 at 20 31 40" src="https://user-images.githubusercontent.com/15108577/84602268-10d92500-ae7e-11ea-878f-ee75e9cd5985.png">

This isn't restricted to Data Studio either. Using the [basic choropleth example](https://www.d3-graph-gallery.com/graph/choropleth_basic.html) if you swap the d3.json to be [https://raw.githubusercontent.com/mshodge/aus_suburbs/master/aus_suburbs.geojson](https://raw.githubusercontent.com/mshodge/aus_suburbs/master/aus_suburbs.geojson) (the same data set as above) the result is the same (blue boxed polygon). Whereas if you use another data set, say [https://raw.githubusercontent.com/tonywr71/GeoJson-Data/master/australian-suburbs.geojson](https://raw.githubusercontent.com/tonywr71/GeoJson-Data/master/australian-suburbs.geojson) it works fine. The second data set is far less complex than the first.

The first data set however plots fine in say QGIS. I've been trying to understand why this is happening. Is there a known issue with complex geometries plotting in D3?

**Comment by mbostock** [comment]
I suspect this is an issue with the winding order of the input. To quote related issues:

> d3-geo uses spherical WSG84 coordinates and edges of a polygon are computed as great-circle shortest paths between successive vertices. It also uses a certain winding convention (see the introduction of https://github.com/d3/d3-geo).

**Comment by mshodge** [comment]
Thanks @mbostock for the fast response. Will have a play around and see if there is a solution. Explains why simplified polygons work.

**Comment by mshodge** [comment]
Thanks @mbostock have used a SHP to GeoJSON CSV approach and plotting is working fine.

Have updated [https://datastudio.google.com/reporting/d991445c-a6ab-4bec-9376-8d6f93467b10](https://datastudio.google.com/reporting/d991445c-a6ab-4bec-9376-8d6f93467b10) to show results.
