### ISSUE TITLE
FitSize to fit an array of objects

### ISSUE THREAD

**Issue by SirCameron** [d3/d3-geo#226]
Is it possible to have projection.fitSize fit an array of objects?
I have a map of only a few countries, and would like the map to nicely position them.

something like: 
```
const projection = geoEquirectangular().fitSize(
    [width, height],
    [object, object]
  );
```

I have tried this.
Is there possibly another way to achieve this?

**Comment by curran** [comment]
I suppose you could compute the bounding box for the objects, then pass that into `fitSize`.

Turf has a utility for this https://turfjs.org/docs/#bbox

**Comment by mbostock** [comment]
You can pass a geometry collection or feature collection to fiSize.
