### ISSUE TITLE
Polygon fill the whole Earth

### ISSUE THREAD

**Issue by jerome-lemaire** [d3/d3-geo#228]
I have an issue with some polygons in my geojson :

My polygon fill the whole Earth. I dont know why.

Working geojson : https://jsfiddle.net/mcr7qode/

Not working geojson : https://jsfiddle.net/q3Lxs8u4/18/

**Comment by curran** [comment]
Have you double checked that no rings in the geometries are anticlockwise?

This sounds similar to this other issue https://github.com/d3/d3-geo/issues/227

**Comment by jerome-lemaire** [comment]
Thanks you, indeed my polygon points where anticlockwise.
Solved by using turf.rewind

**Comment by curran** [comment]
Nice!
