### ISSUE TITLE
Update rollup and rollup-plugin-terser

### ISSUE THREAD

**Issue by martinfrances107** [d3/d3-geo#233]
I have just enabled automated security audits on my github account and the bot reported a security warning for my local copy of d3-geo which I would like to fix upstream.

serialize-javascript has a high severity warning 

which is pulled in as a result of our outdated use of rollup-plugin-terser

my proposal it we bump the major version of both rollup and rollup-plugin-terser

When I test locally every works smoothly... I am about to file a PR.

here is the diff of package.json

-    "rollup": "1",
-    "rollup-plugin-terser": "5",
+    "rollup": "^2.45.2",
+    "rollup-plugin-terser": "^7.0.2",

**Comment by mbostock** [comment]
Fixed in #238.

**Comment by martinfrances107** [comment]
Thank you
