### ISSUE TITLE
Incorrect map of India is rendered

### ISSUE THREAD

**Issue by harora-ot** [d3/d3-geo#247]
The below image shows a map drawn using this library version 1.11.3
The map of India is incorrect and does not show the disputed areas of Kashmir. To use such a map is insensitive towards the Indian population. This should be corrected to reflect the disputed areas that are under Pakistan and China. The dotted lines need to be drawn, they are significant to a lot of people.

![image](https://user-images.githubusercontent.com/48446376/129623339-dbdea05d-317a-4a47-a591-9d17b0873a23.png)

**Comment by mbostock** [comment]
D3 doesn’t provide any geographic boundaries, so this data is coming from elsewhere. You might be looking at something from Natural Earth Data, but I can’t tell from a screenshot alone.

https://github.com/nvkelso/natural-earth-vector

**Comment by harora-ot** [comment]
Here is a link for refrence. Any pointers on how to tweak this?
 http://embed.plnkr.co/i2eLwxweLJhuUgTuOS4x/

**Comment by curran** [comment]
@harora-ot The first step is finding out where `states.json` comes from in that example. That example does not cite any source for that data file.

The next step is finding a data source for boundaries that fits your needs. Maybe find an online map that has the boundaries you would expect to see, then research what data source they are using.

Also, Natural Earth does provide disputed boundaries, which you could pull into the map to highlight them.

https://www.naturalearthdata.com/downloads/50m-cultural-vectors/

![image](https://user-images.githubusercontent.com/68416/129781283-c47f8b92-fc39-4d08-97af-06b2fa8aaa07.png)

Good luck!

**Comment by harora-ot** [comment]
Thanks, appreciate the direction given. I Will circle back once I am able to sort this

**Comment by i-am-gg** [comment]
Hey @harora-ot were you able to sort this? I still see the map to be incorrect
![image](https://github.com/user-attachments/assets/58ec0e02-5b92-4dc7-bd8e-0f196ea67a6a)
