### ISSUE TITLE
d3.geoPath, d3.geoProjection and basic projections

### ISSUE THREAD

**Issue by chrisuehlinger** [d3/d3-geo#25]
In the geoCircle PR discussion, [you talked about](https://github.com/d3/d3-geo/pull/21#issuecomment-224956531) pulling geoProjection and the rest of d3.v3.geo into d3-geo for d3 v4.0, and then breaking them out into d3-geo-projection for v5.0 when we do the new graphics pipeline. 

I took a dive through the code, and found that geo.projection and geo.path have a circular dependency between them, and that geo.path has a dependency on the albers-usa projection (which then depends on other projections, etc.). It looks like the only way to migrate these over is to move geo.path, geo.projection and the basic projections over all at once (along with the `clip-*` and path-*` components). If this sounds like the right thing to do, I can get started on doing this all locally this week. (The eventual PR will have to wait for geoArea, geoCentroid and geoBounds to be merged)

Also, I've got a couple questions regarding the desire to eventually break d3.geoProjection into its own module. I understand the value of the d3-geo functions as tools for doing spherical math, but without projections, no one will be able to render maps. Do you see a lot of use cases where developers might import `d3-geo` and not need `d3-geo-projection`?

**Comment by mbostock** [comment]
d3-geo-projection would include d3.geoPath, too, yes. But at any rate, we’re going to put all the d3.geo stuff into d3-geo for 4.0, excepting only the extended projections which are in d3-geo-projection.

I’m actually going to work on this today and try to get as much done as possible. There are only two weeks left before my self-imposed July deadline. I’ve made good progress on the [release notes](https://github.com/d3/d3/blob/master/CHANGES.md) but this is the last major piece of the code, so I’m going to try to finish the port today.

**Comment by chrisuehlinger** [comment]
Cool, I've got a port of geoBounds ready to go once you merge geoArea.

**Comment by mbostock** [comment]
Thanks!

**Comment by mbostock** [comment]
>  I understand the value of the d3-geo functions as tools for doing spherical math, but without projections, no one will be able to render maps. Do you see a lot of use cases where developers might import d3-geo and not need d3-geo-projection?

I don’t see d3-geo being hugely useful without d3-geo-projection, but it might be moderately useful… and maybe there are different geographic projection abstractions (libraries) you might want to use? Separating our projection implementation from spherical math allows you to pick which projection library you want to use while still using our spherical math utilities if desired.

I’d rather err on the side of keeping things separated and keeping the modules smaller, and it seems like a reasonable split, here, given the complexity of geographic projection.
