### ISSUE TITLE
d3.geoBounds returning confusing output

### ISSUE THREAD

**Issue by mrshll** [d3/d3-geo#253]
I've been trying to understand the output of `getBounds`. Regardless of the features I've passed it, I get the same output:

```
[[-180, -90], [180, 90]]
```

Here is a test with a single square feature over the state of Massachusetts in the US.

![image](https://user-images.githubusercontent.com/339996/136867930-6b7789d7-e205-47ec-a2d2-0d5113f8549a.png)

**Comment by mbostock** [comment]
I suspect that your winding order is reversed.
