### ISSUE TITLE
Geographic or Geodetic

### ISSUE THREAD

**Issue by gonzobard777** [d3/d3-geo#264]
Latitude and longitude expected Geographic or Geodetic?
e.g.:
```typescript
import {geoStereographic} from 'd3-geo';

const projection = geoStereographic();
const point = projection([longitude, latitude]);
```

**Comment by jrus** [comment]
This is the spherical stereographic projection. If you want a proper conformal projection of the ellipsoid you need to use the "conformal" latitude.

https://en.wikipedia.org/wiki/Latitude#Conformal_latitude
