### ISSUE TITLE
Mercator. Getting boundary values by longitude

### ISSUE THREAD

**Issue by dowhileforeach** [d3/d3-geo#273]
**I use d3-geo 3.1.0**

# Without rotation (everything works well)

![angle0](https://user-images.githubusercontent.com/31113236/209872916-e228e6e6-08ef-4bb6-89ca-1d28892ff0d1.png)

```javascript
const geoToProj = geoMercator().rotate([0, 0, 0]);

console.log('[-180,0] ->', geoToProj([-180,0]));
console.log('[180,0] ->', geoToProj([180,0]));
```
output:
```shell
[-180,0] -> [-0.5, 250]
[180,0] -> [960.5, 250]
```

it seems there are no problems here, the only thing is not clear why -0.5 and 960.5, **and not 0 and 960**...

# Rotate, lambda -10 (unexpected behavior)

![angle-10](https://user-images.githubusercontent.com/31113236/209872929-0cf788d5-3d00-41a5-9d11-81a44a7793c6.png)

```javascript
const geoToProj = geoMercator().rotate([-10, 0, 0]);

console.log('[-170,0] ->', geoToProj([-170,0]));
console.log('[190,0] ->', geoToProj([190,0]));

const roundD3Bound = (n) => n - 0.0000000000001;
console.log('[190 rounded,0] ->', geoToProj([roundD3Bound(190),0]));
```
output:
```shell
[-170,0] -> [-0.5, 250]
[190,0] -> [-0.49999999999994316, 250]
[190 rounded,0] -> [960.4999999999998, 250]
```
I rotated the projection to lambda -10 degrees.
Accordingly, I expect the longitude boundaries to be -170 and 190.
As a result, the geographic point `[-170,0]` on the projection `[-0.5, 250]`
**matches** the geographical point `[190,0]` on the projection `[-0.49999999999994316, 250]`.

And only such a geographical point `[189.9999999999999, 0]` on the projection will be where it is expected `[960.4999999999998, 250]`.

[Check it. Stackblitz](https://stackblitz.com/edit/js-afgqav?file=index.js)

# Question

Is there a method to get the longitude boundary values for the projection?
That is, for example, for projection `geoMercator().rotate([-10, 0, 0])`
I call the method "give boundary values for longitude" and it returns to me `left=-170`, `right=189.9999999999999`?

**Comment by mbostock** [comment]
You can’t rely on [190,0] being distinct from [-170, 0]; they represent the same point on the sphere. Same with [-180, 0] and [180, 0]; it’s somewhat coincidental that it works in this case due to floating point. If you want to compute the bounds of something, use [path.bounds](https://github.com/d3/d3-geo/blob/main/README.md#path_bounds), say with `{type: "Sphere"}` for the entire globe.

**Comment by dowhileforeach** [comment]
Mike, thank you for the hint about using `path.bounds`.
As a result, the boundary values of the mercator, expressed in geographical coordinates, now I get this way:

```javascript
function mercatorGeoBounds(lambda: number) {
  const geoToProj = geoMercator().rotate([lambda, 0, 0]);
  const projToGeo = geoToProj.invert;
  const [leftTopBoundPointOnProj, rightBottomBoundPointOnProj] = geoPath().projection(geoToProj).bounds({type: 'Sphere'});
  const leftTopBoundPoint = projToGeo(leftTopBoundPointOnProj);
  const rightBottomBoundPoint = projToGeo(rightBottomBoundPointOnProj);

  const [lonLeft, latTop] = leftTopBoundPoint;
  return {
    lonLeft,
    lonRight: (lonLeft + 360) - 0.000000000001,
    latTop,
    latBottom: rightBottomBoundPoint[1],
  };
}
```
