### ISSUE TITLE
Mercator with rotate. Incorrect conversion from projection to geographic coordinates

### ISSUE THREAD

**Issue by dowhileforeach** [d3/d3-geo#274]
I create mercator converter with rotation by lambda -50 degrees:
```javascript
const geoToProj = geoMercator().rotate([-50, 0, 0]);
```
Direct conversion from geographic coordinates of the point `[200, 0]` to a projection works fine:
```javascript
geoToProj([200,0]) -> [880.4166666666667, 250]
```

But the inverse conversion of the same projection point `[880.4166666666667, 250]` leads to an incorrect result:
```javascript
geoToProj.invert([880.4166666666667, 250]) -> [-159.99999999999997, -1.2722218725854067e-14]
```
shouldn't the result of the inverse conversion be close to the point `[200, 0]`?

[Check It. Stackblitz](https://stackblitz.com/edit/js-pgmhap?file=index.js)

**Comment by mbostock** [comment]
The expected range of longitude is ±180, so 200 is the same as -160.

**Comment by dowhileforeach** [comment]
Surprisingly, proj4js has exactly the same bug:

```javascript
const proj4 = require('proj4');

const geoToProj = proj4('+proj=merc +lon_0=50 +ellps=WGS84 +datum=WGS84');

console.log(geoToProj.forward([200,0])); // --> [16697923.618991036, 0]
console.log(geoToProj.inverse([16697923.618991036, 0])); // --> [-160, 0]
```
[Check It. Stackblitz](https://stackblitz.com/edit/typescript-rjspij?file=index.ts)

Apparently, there is some technical problem to take into account rotation by lambda when converting proToGeo...

**Comment by mbostock** [comment]
It’s not a bug. That’s the expected behavior as I described due to the nature of spherical/cylindrical coordinates.
