### ISSUE TITLE
Mercator Map centered on the Pacific

### ISSUE THREAD

**Issue by Calvin1121** [d3/d3-geo#285]
Apologies if this is a simple case of me being blind to the obvious, but I am trying to put together a page that shows a map of the world (data sourced from a GEOJSON file) in Mercator projection centered on the Pacific. I.e. Europe on the left, America on the right and Australia in the middle.
![1Rxqa](https://github.com/d3/d3-geo/assets/31435496/efec996c-8834-4b8b-a84b-5445096140c9)

**Comment by mbostock** [comment]
Try projection.rotate.
