### ISSUE TITLE
Projection tests.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo#34]
It would be nice to have tests that take world-110m.json as input and verify compatibility with D3 3.x.

**Comment by Fil** [comment]
Unfortunately to use `world-110m.json` one would have to depend on topojson. I'm not sure this is what we want here.

I've created a test with a random `countries.geo.json`; is it the kind of test you had in mind?


```
var tape = require("tape"),
    fs = require("fs"),
    d3_geo = require("../../");

var projection = d3_geo.geoEquirectangular()
    .scale(900 / Math.PI)
    .precision(0);

tape("projection equirectangular: center", function(test) {
  test.deepEqual(projection([0,0]), [ 480, 250 ]);
  test.end();
});

tape("projection equirectangular: countries geojson", function(test) {
  var world = JSON.parse(fs.readFileSync("test/data/countries.geo.json", "utf-8"));
  var path = d3_geo.geoPath()
  .projection(projection);
  test.equal(path(world).replace(/[13579]/g, '').length, 159941);
  test.end();
});
```

**Comment by Fil** [comment]
(`path(world).replace(/[13579]/g, '').length` is here just to list a very short result in the test file; it could be a crc32 or anything else)

**Comment by mbostock** [comment]
A topojson dependency isn’t strictly required since you can make a copy of world-110m.json, and you could convert it to GeoJSON to avoid the dependency on the client library. But I don’t see any issue with having a devDependency on topojson for the purpose of testing.

**Comment by mbostock** [comment]
It might be nice to do image-based testing since these are much easier to review than looking at the coordinates of the generated geometry by hand.

**Comment by mbostock** [comment]
Also automate these tests https://jasondavies.com/maps/clip/
