### ISSUE TITLE
circle.radius() is confusing

### ISSUE THREAD

**Issue by Spaxe** [d3/d3-geo#42]
D3 4.0 renamed [circle.angle to circle.radius](https://github.com/d3/d3/blob/master/CHANGES.md#geographies-d3-geo). I'm having trouble understanding the concepts, so I hope someone can enlighten me.

The documentation currently says (emphasis mine):

**[circle.radius](https://github.com/d3/d3-geo#circle_radius)([radius])**

> If radius is specified, **_sets the circle radius to the specified angle in degrees_**, and returns this circle generator. The radius may also be specified as a function; this function will be invoked whenever a circle is generated, being passed any arguments passed to the circle generator. If radius is not specified, returns the current radius accessor, which defaults to:

In the source code, it appears the `radius` variable is passed into `cos()` and `sin()`, which has to be an angle.

**Comment by Fil** [comment]
https://github.com/d3/d3-geo#geoCircle

geoCircle is a polygon generator that approximates a circle on the sphere. Think "Arctic circle", not "a circle drawn on flat paper with a compass".

If you set its center on the pole, and its radius at 90°, you get a line on the Equator. With a radius of 23.43° you get the Arctic circle (23.43 = 90° for North Pole - 66° 34′ 0″ N).

So indeed the radius is defined as an angle; but remember, this circle is a polygon generator, not a "circle". In most projections it is going to be shown as a straight line. It's only in 3D (x,y,z - space) that this circle is drawn as a "circle". And it's true that, in that case, the drawing has a radius, that would be `r * sin(radius)`.

HTH

**Comment by Spaxe** [comment]
This has gotta be the greatest confusing terminology invented in Mathematics. Thanks, @Fil.

OK, so are you saying that the 'radius' is actually the longitude, and the circle on the sphere is always parallel to the equator line?

I'm reading https://en.wikipedia.org/wiki/Great-circle_distance and the diagram has a rotated circle, which confused me further. One radius (read: angle) can't be enough to define this circle, unless it's always going to be parallel to the equator line.

**Comment by Fil** [comment]
The circle is a parallel if (and only if) the circle is centered on one of the poles.
See https://github.com/d3/d3-geo#circle_center

**Comment by Spaxe** [comment]
Set the centre to `[-90, 0]` (North pole, right?) and radius to `90`, you get the 'equator' on the sphere ... I think?

I drew this picture to make sure my understanding is 100%.

![20160627_174243_hdr-2](https://cloud.githubusercontent.com/assets/708395/16372211/da11764a-3c8e-11e6-8272-9ca7cdcc6547.jpg)

**Comment by Fil** [comment]
Your drawing is correct, but North Pole is `[0,90]`. You can play with the following block if you want to see what happens when you change parameters and values.
http://blockbuilder.org/Fil/cafad70aea7ec49d787e123b1026db06

It defines a red and a blue "centers", with a set of circles drawn from these centers and with a radius going from 5° to 90°.

As you can see on this equirectangular the circles centered on the North Pole (the red ones) are drawn as straight lines, whereas the circles centered on WashingtonDC are drawn as, well, geographic circles :))

![geocircle](https://cloud.githubusercontent.com/assets/7001/16372755/c3c1dd20-3c4e-11e6-9dbf-2f54fdc59275.png)

**Comment by Spaxe** [comment]
Thanks, that makes perfect sense now!

**Comment by phocks** [comment]
Hi there I am looking for way to draw these circles with a stroke, but not have it draw the stroke on the outside edge of the map. I thought I found an article about how to convert the geoCircle to a GeoJSON and then pass it to the path projection but I can't seem to find it anywhere. Any help would be useful. Thanks.
