### ISSUE TITLE
Polyhedral projections.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo#47]
It would be nice to update these to d3-geo 1.1+ and release them as a D3 module:

https://github.com/d3/d3-plugins/tree/master/geo/polyhedron

**Comment by Fil** [comment]
related examples:
https://github.com/d3/d3-geo-projection/commit/48bb95222b33e391236aa89da39e3b1e209010d1

research projects:
https://github.com/d3/d3-geo-projection/issues/6
https://github.com/d3/d3-geo-projection/issues/25

**Comment by Fil** [comment]
I did some tests here http://bl.ocks.org/Fil/b369b7fea5daa486a3ec8d6829d6b0b9 and there doesn't seem to be any problem. But I'm not sure we need yet another module: can't we simply package them together with https://github.com/d3/d3-geo-projection ?

**Comment by Fil** [comment]
done

**Comment by mbostock** [comment]
This is great! Sorry I haven’t had a chance to review your pull request. I’m going to close this issue since and track this work with your pull request, d3/d3-geo-projection#69.
