### ISSUE TITLE
d3.geoPath.context() confuses Closure Compiler

### ISSUE THREAD

**Issue by pallosp** [d3/d3-geo#58]
The compiler complains that contextStream doesn't have pointRadius property.

PathString and PathContext should apparently be instantiated without new, since they return the created objects.

https://github.com/d3/d3-geo/blob/master/src/path/index.js

```
  path.context = function(_) {
    if (!arguments.length) return context;
    contextStream = (context = _) == null ? new PathString : new PathContext(_);
    if (typeof pointRadius !== "function") contextStream.pointRadius(pointRadius);
    return path;
  };
```

**Comment by mbostock** [comment]
It was my intent to implement PathString and PathContext without closures so I’ve now made that change. Thanks for the reminder.

**Comment by pallosp** [comment]
Thanks for the super quick fix.
