### ISSUE TITLE
How to flip y with d3.geoIdentity()?

### ISSUE THREAD

**Issue by herrstucki** [d3/d3-geo#68]
I'm trying to resize a preprojected geojson:

```
geoproject 'd3.geoIdentity().fitExtent([[0,0],[960,500]], d)'
```

… which leads to a vertically flipped output because in the original coordinate system, the origin is at the _bottom_ left instead of the top. Using an extent of `[[0,500],[960,0]]` didn't help (that just rotated everything by 180°).

With the old topojson I would just do `topojson --width=960 --height=500`. Am I missing something?

**Comment by mbostock** [comment]
You can’t use d3.geoIdentity for this. You need to use the more general d3.geoTransform. Let me find or cook up an example…

**Comment by mbostock** [comment]
Yeah, [here it is](https://github.com/d3/d3-geo-projection/issues/77#issuecomment-257499669):

```bash
shp2json nad83.shp | \
  geoproject 'd3.geoTransform({point: function(x, y) { this.stream.point(x, -y); }})' | \
  geoproject 'd3.geoIdentity().fitSize([960, 500], d)' | \
  geo2svg > test.svg
```

So you have to chain two geoprojects together. Let me think about whether it’s possible to compose these transitions (which was the goal of the new graphics pipeline, which I haven’t had time to work on…).

**Comment by herrstucki** [comment]
Very nice, thanks!

**Comment by mbostock** [comment]
Added [*identity*.reflectY](https://github.com/d3/d3-geo/blob/master/README.md#identity_reflectY) in [d3-geo 1.4](https://github.com/d3/d3-geo/releases/tag/v1.4.0) to make this easier and more obvious.

**Comment by herrstucki** [comment]
Works like a charm, thank you!
