### ISSUE TITLE
Cannot synchronize rotations of D3 and Three

### ISSUE THREAD

**Issue by dongli** [d3/d3-geo#74]
I would like to use D3.js with Three.js, where D3.js displays Natural Earth data, and Three.js renders the shaded meteorological data. The mouse interaction is needed, currently I am focusing on rotation (or drag). I use `d3.drag()` to handle drag event. AFAIK, Three.js uses quaternion for rotation, and D3.js uses Euler angles, and quaternion is better than Euler angles.

I managed to set quaternion for Three.js, and successfully rotate the sphere, but the challenging part is to synchronize the two! I failed to work it out no matter what I did. Any idea?

**Comment by Fil** [comment]
d3 can be tweaked to use quaternions, as demonstrated by @jasondavies in https://www.jasondavies.com/maps/rotate/
however as Jason's code does not seems to be available anymore, it would be nice if we could use the three.js method instead and move forward

**Comment by dongli** [comment]
@Fil I have followed [this quaternion solution](http://bl.ocks.org/ivyywang/7c94cb5a3accd9913263), and the rotation of D3.js is better. But when I rotate Three.js with the computed quarternion, they are still not consistent. Should I transform that quarternion since D3.js and Three.js use different coordinate systems?

**Comment by Fil** [comment]
I think there are two issues:
1) accumulate the drag and convert this movement to some rotation. I have a poor man's version [here](http://bl.ocks.org/Fil/1c2f954201523af16280db018ddd90cc), but quaternions seem to be better suited for this task.
2) keep both rotations in sync, d3-geo's [.rotate()](https://github.com/d3/d3-geo#projection_rotate), and the [camera angle for three.js](https://threejs.org/docs/api/math/Quaternion.html).

Can you share a simple example on blockbuilder.org so we can play with it?

**Comment by jrus** [comment]
Generally the best thing to do is accumulate a rotation as a quaternion, then convert it to a 3x3 matrix when you want to apply it to a list of vectors.

**Comment by dongli** [comment]
@Fil I have created two versions on blockbuilder ([v1](http://bl.ocks.org/dongli/5d5603da007d9a48420379d87fbd98c2) and [v2](http://bl.ocks.org/dongli/e9291c411cd7ed409e71bcd14d681952)). `v1` (using quaternion rotation) failed and `v2` (using two axes Euler angles rotation) succeeded.

**Comment by dongli** [comment]
@jrus How to do the matrix multiplication in `d3-geo`?

**Comment by mbostock** [comment]
I made a version here: https://bl.ocks.org/mbostock/7ea1dde508cec6d2d95306f92642bc42

**Comment by dongli** [comment]
@mbostock The link you provided seems broken?

**Comment by mbostock** [comment]
Works for me?

**Comment by dongli** [comment]
@mbostock I finally saw your version, but there is no Three.js stuff. We can rotate D3 by using Euler angles converted from quaternion, but it cannot be synchronized with Three.js which use quaternion internally, where D3.js does not?

**Comment by Fil** [comment]
I assembled Mike's code with your example and it works after rotating the versor, which for some reason* isn't using the same referential.
http://bl.ocks.org/Fil/9ed0567b68501ee3c3fef6fbe3c81564

* The trick was
`var q = new THREE.Quaternion(-q1[2], q1[1], q1[3], q1[0])`

Thank you!!

**Comment by dongli** [comment]
@Fil Well done! Thanks! I will use this version. I missed that trick which I have already noticed previously by drawing the coordinate systems of them on the paper.

**Comment by Fil** [comment]
Great. Can you share the drawing to help with the documentation?

**Comment by dongli** [comment]
@Fil Your version is good. It would be great if this `versor.js` can be built into `d3-geo`.

**Comment by mbostock** [comment]
It’s quite possible that I borked the implementation somehow.

**Comment by mbostock** [comment]
Maybe a d3-geo-rotate plugin that combines the drag behavior and a projection to rotate it interactively?

**Comment by Fil** [comment]
I don't know much about three.js but from what I gather, its (x,y,z) referential has:
- x to the right (the red dot in my example is x=1, y=0, z=0)
- y to the top (the green dot is x=0, y=-1, z=0)
- z to front of the screen (blue dot is x=0, y=0, z=1)

With versor.js 0.0.0:
- red dot `versor.cartesian([90,0]) => [x=0, y=1, z=0]`
- green dot `versor.cartesian([0,-90]) => [x=0, y=0, z=-1]`
- blue dot `versor.cartesian([0,0]) => [x=1, y=0, z=0]`


Reference code:
```
versor.cartesian = function(e) {
  var l = e[0] * radians, p = e[1] * radians;
  return [cos(p) * cos(l), cos(p) * sin(l), sin(p)];
};
```

I'm not sure it all needs to be changed to match perfectly the three.js model — for example, d3 inherently works with y pointing down not top.

**Comment by mbostock** [comment]
Yeah, I used the [same definition](https://github.com/d3/d3-geo/blob/v1.4.0/src/cartesian.js#L7-L10) as d3-geo. I guess that’s reasonable, but if there is a strong convention, I think it would be fine to change it.

**Comment by Fil** [comment]
I think it's perfectly fine to keep d3 referential as it is, and have people fiddle around if they need to map it to other softwares' conventions. I can work on a nicer example to help document it.

(As for packaging, I have no preference, but it sure will be a super useful addition to d3, it was really difficult to do properly.)

**Comment by jrus** [comment]
For geographical coordinates, I believe the usual convention is for *x* to point toward the gulf of Guinea (0°N, 0°E), *y* to point toward the Indian ocean a bit west of Indonesia (0°N, 90°E), and *z* to point toward the north pole.

**Comment by Fil** [comment]
My notes from the example at http://bl.ocks.org/Fil/9ed0567b68501ee3c3fef6fbe3c81564 :  

three.js

```
    ^ Y
    |
    |
    |
    --------———> X
     \
      \
       Z
```


d3 cartesian(lambda, phi)

```
    ^ Z
    |
    |
    |
    --------———> Y
     \
      \
        X
```


So d3 seems to be on the geographic convention you mention.


I now have a secondary issue. I was trying to cook up an example, and show that we could move the (three.js) camera, or the light source, instead of rotating the object { the story being: rotating the object = watching Earth spin with time ; rotating the camera = watching Earth from the ISS }. But in this case everything is suddenly off when the cursor drags goes near the edge, and I don't understand why:
http://blockbuilder.org/Fil/ad107bae48e0b88014a0e3575fe1ba64

**Comment by dongli** [comment]
@Fil The camera rotation was a case that I have struggled with several days, and I gave it up since when rotate across pole the camera will flip to keep up direction. So I think rotate sphere is the more natural choice.

PS: I hope the `versor` functions can be baked into `d3-geo` so that we don't need to write it down somewhere in application as a hack.

**Comment by Fil** [comment]
Figured out why the camera rotation is wrong: by setting camera position and lookAt(center), we have set 5 of its 6 degrees of freedom (`camera.position.x,y,z` ; `camera.rotation.x,y` ); but you still have to figure out its roll (set `camera.rotation.z = 2*Math.PI*Math.random()` for some fun). 
So, not a d3 issue. Let me know if we move the discussion somewhere else.

**Comment by Fil** [comment]
Referencing here:
https://github.com/Fil/versor
https://github.com/Fil/d3-inertia
