### ISSUE TITLE
Front clip angle?

### ISSUE THREAD

**Issue by zyklus** [d3/d3-geo#77]
I'm wondering if there is, or if it's feasible to add, a front clipping angle?

For an example like this: https://bl.ocks.org/Fil/02e6d4c63ab52d202ca9d922b4b9000f

The backface of the continents is a just a full rendering clipped to > 90° (107.3° in this case), and then the frontface is drawn on top of that.  This is a waste and I'm trying to find a way to *just* draw the [90°, 107.3°] range

**Comment by mbostock** [comment]
The short answer is that it’s not currently possible. You could use Canvas or SVG to clip out the front-facing hemisphere for the orthographic projection, but that’s after everything has been projected, so it wouldn’t be as efficient as doing it as part of projection.

I just opened #78 to summarize work that I did a couple years ago on making the projection system more modular that could theoretically allow multiple clipping passes. If you are interested in contributing to d3-geo to add functionality such as this, please take a look.

**Comment by zyklus** [comment]
Great, thanks for the response.  The work you've done there looks really promising, but unfortunately I'm not sure how feasible it is for me to contribute at the moment considering that this isn't (it looks like) integrated into d3 at the moment.  If you plan to start down the road of integrating this into core, I'd be happy to contribute where I can!
