### ISSUE TITLE
geoBounds returns inconsistent results

### ISSUE THREAD

**Issue by jnyrup** [d3/d3-geo#80]
Computing the geoBounds of a feature consisting of a Linestring between Rio de Janeiro and Tokyo returns a different bottom than for the reverse route.

https://jsfiddle.net/fz7u1ro9/1/

Changing the geometry type to MultiPoint keeps the results consistent.

**Comment by mbostock** [comment]
I am able to reproduce this issue.

https://bl.ocks.org/mbostock/6f404096905bbc69752505a457783492

**Comment by jnyrup** [comment]
That was quick! Thank you very much.
