### ISSUE TITLE
d3.geoBounds returns global bbox for small right-hand-rule oriented polygon

### ISSUE THREAD

**Issue by tyrasd** [d3/d3-geo#83]
The following code falsely(?) returns a global bounding box:

    d3.geoBounds({type: "Feature", properties:{}, geometry: {type: "Polygon", coordinates:[[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]]}})

(this ticket follows https://github.com/d3/d3-geo/pull/79#issuecomment-280862551)

**Comment by mbostock** [comment]
Folding into d3/d3-geo#79.
