### ISSUE TITLE
d3.geoPath breaks in Internet Explorer/Edge (d3 v4.5.1)

### ISSUE THREAD

**Issue by joedjc** [d3/d3-geo#84]
The error console gives the following error:

Cannot redefine non-configurable property 'length' at line:

```js
var path = d3.geoPath()
    .projection(projection);
```

The error can be reproduced by opening the example (https://bl.ocks.org/mbostock/5593150) in either internet explorer 11 or Edge.

Reverting to d3 v4.5.0 resolves the issue.

**Comment by mbostock** [comment]
Argh. I mistakenly shipped [*path*.length](https://github.com/d3/d3-geo/blob/master/README.md#path_length) in a patch release, [1.4.1](https://github.com/d3/d3-geo/releases/v1.4.1). (See 094490829d95da3758000c73c200f3baa09313cb.) So d3-geo 1.4.1 should have been 1.5.0, and 1.4.2 should be 1.5.1. And worse, d3 4.5.1 should ben 4.6.0.

However, given that we simply can’t support *path*.length in IE/Edge, and given that the feature  recently released and undocumented and unintentional, I think it makes the most sense to deprecate d3-geo 1.4.1, d3-geo 1.4.2, d3 4.5.1, and then release d3-geo 1.50 and d3 4.6.0 with *path*.length renamed (or removed).

**Comment by joedjc** [comment]
Cool, thanks for looking into it so quickly!

**Comment by mbostock** [comment]
Thanks for the report, and sorry for my mistake. I’ve released d3-geo 1.5.0 and d3 4.6.0 with the method renamed to *path*.measure.
