### ISSUE TITLE
add d3.geoNull for working with already projected geo data

### ISSUE THREAD

**Issue by gka** [d3/d3-geo#97]
I know that we're supposed to do just `d3.path().projection(null)` but then there's no way to use the nice `proj.fitSize` functions. `d3.geoEquirectangular` gets pretty close to `geoNull` but it's doing weird things to the geometry.

**Comment by mbostock** [comment]
What you are looking for is called [d3.geoIdentity](https://github.com/d3/d3-geo/blob/master/README.md#geoIdentity).

**Comment by gka** [comment]
oh thanks! 👍
